### ISSUE TITLE
Does this work with UseCookieAuthentication?

### ISSUE THREAD

**Issue by jchannon** [onatm/Owin.Antiforgery#1]
I'm trying to do something like this http://stackoverflow.com/questions/15574486/angular-against-asp-net-webapi-implement-csrf-on-the-server ie/create a CSRF token based on a authorised cookie

However I'm having issues reading the Set-Cookie from the cookie middleware Microsoft.Owin.Security.Cookies in my own middleware.

I was wondering if you'd be interested in looking at this?

**Comment by onatm** [comment]
I'm closing the issue since you solved it here: http://blog.jonathanchannon.com/2015/04/27/cookie-authentication-angularjs-csrf-owin-mono/
